version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: casabenetti
      POSTGRES_PASSWORD: secretcasabenetti
      POSTGRES_DB: mi_basedatos
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: