version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: casabenetti
      MONGO_INITDB_ROOT_PASSWORD: secretcasabenetti
      MONGO_INITDB_DATABASE: mi_basedatos
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: